# **Numpy**

In [2]:
# pip install numpy

In [3]:
import numpy as np

my_list=[1,2,4]
type(my_list)

list

In [4]:
my_arr=np.array(my_list)
type(my_arr)

numpy.ndarray

In [5]:
my_arr

array([1, 2, 4])

In [6]:
my_arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
my_arr2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(1,101,20)

array([ 1, 21, 41, 61, 81])

In [9]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
#it will evenly split 
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [12]:
np.random.rand(5,2) 

array([[0.87266189, 0.369618  ],
       [0.26801271, 0.57243301],
       [0.57054495, 0.64151216],
       [0.89964388, 0.36483947],
       [0.13017942, 0.60936473]])

In [13]:

np.random.randn(10)

array([-0.65584759,  2.18098008, -1.71992064, -0.00872324, -0.2361893 ,
        0.57986859, -1.26609473,  0.82371312,  1.34717289,  0.8935206 ])

In [14]:
np.random.randint(0,100,10)

array([40, 98, 67, 28, 77, 15, 47, 32, 19, 60])

In [15]:
np.random.rand(4)

array([0.94077123, 0.83171156, 0.94315031, 0.95498466])

In [16]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [17]:
arr=np.arange(0,25)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
arr.min(),arr.max()

(0, 24)

In [19]:
arr.dtype

dtype('int32')

In [20]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr[8]

8

In [22]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [23]:
arr=np.arange(1,10)

In [24]:
arr+5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
arr*3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])